
name: Template
channels:
  - r
  - conda-forge
  - bioconda
  - defaults
  - anaconda

dependencies:
  - python=3.6
  - tabix
  - gfortran_linux-64=7.3
  - r-base=3.2.2 
  - r-essentials=1.1
  - r-ggplot2
  
