name: docker-build-push

on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - main
env:
    dockerhub_repository: template_r_project
    dockerhub_organization: richardslab
jobs:
  variables:
    runs-on: ubuntu-latest
    outputs:
      date: ${{ steps.date.outputs.value }}
      branch_tag: ${{ steps.branch.outputs.value }}
      tag: ${{ steps.tags.outputs.value }}
    steps:
      - 
        name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v3.x
      -   
        name: Get current date
        id: date
        run: echo "::set-output name=value::$(date +'%Y-%m-%d')"
      - 
        name: Get Branch tag
        id: branch
        run: echo "::set-output name=value::${{env.dockerhub_organization}}/${{env.dockerhub_repository}}:${{steps.date.outputs.value}}_${{env.GITHUB_REF_SLUG}}"
      - 
        name: Get Latest tag
        id: latest
        run: echo "::set-output name=value::${{env.dockerhub_organization}}/${{env.dockerhub_repository}}:latest"
      - 
        uses: haya14busa/action-cond@v1
        id: tags
        with:
          cond: ${{ env.GITHUB_REF_SLUG == 'main' }}
          if_true: ${{env.branch_tag}}, ${{env.latest_tag}}
          if_false: ${{env.branch_tag}}
        env:
          branch_tag: ${{steps.branch.outputs.value}}
          latest_tag: ${{steps.latest.outputs.value}}
  build_docker:
    needs: variables
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      - 
        name: Show space available
        run: df -h .
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - 
        name: Show space available
        run: df -h .
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - 
        name: Show space available
        run: df -h .
      - 
        name: Get hash key for cache
        id: hash
        uses: theowenyoung/folder-hash@v2.0.1
        with:
          path: installation
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ steps.hash.outputs.hash }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Show space available
        run: df -h .
      -
        name: Show variables
        run: |
          echo date = ${{ needs.variables.outputs.date }}
          echo tags = ${{ needs.variables.outputs.tag }}
          echo branch = ${{ needs.variables.outputs.branch_tag }}
          echo hash = ${{ steps.hash.outputs.hash }}
      -
        name: Build and push branch
        uses: docker/build-push-action@v2
        with:
          context: installation
          push: true
          tags: ${{ needs.variables.outputs.tag }}
          builder: ${{ steps.buildx.outputs.name }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
  test_conda_with_farjoun_action:
    needs: needs: [variables,build_docker]
    steps:
      -
        uses: yfarjoun/docker-run-action
        with:
          image: ${{ needs.variables.tags.env.branch_tag }}  
          run: conda env list
  test_conda_info:
    runs-on: ubuntu-latest
    needs: [variables,build_docker]
    container: ${{ needs.variables.tags.env.branch_tag }} 
    steps:
      - 
        name: hello world
        run: |
          echo "first line"
          echo "second line"

      - name: Show space available
        run: df -h .
      - name: show env
        run: env
      - name: conda
        run: conda env list
      - name: test running in docker
        run: /usr/local/bin/run.sh
  test_r_png:
    needs: [variables,build_docker]
    runs-on: ubuntu-latest
    container: ${{ needs.variables.tags.env.branch_tag }} 
    steps:
      -
        name: Show space available
        run: df -h .
      -
        name: run docker test png
        run: Rscript -e 'png()' 
  test_r_2SMR:
    needs: [variables,build_docker]
    runs-on: ubuntu-latest
    container: ${{ needs.variables.tags.env.branch_tag }} 
    steps:
      -
        name: run docker test two-sample-mr
        run: Rscript -e 'library(ggplot2)'
  test_docker:
    needs: [variables,build_docker]
    runs-on: ubuntu-latest
    steps:
      - name: get-image
        id: image
        run: docker pull ${{needs.variables.tags.env.branch_tag}}"
      - name: tag image
        run: docker tag ${{needs.variables.tags.env.branch_tag}} test:latest 
      -
        name: test0
        uses: docker://richardslab/template_r_project:latest
        with:
          args: conda list
      -
        name: test1
        uses: docker://richardslab/template_r_project:latest
        with:
          args: conda info
      -
        name: test2
        uses: docker://richardslab/template_r_project:latest
        with:
          entrypoint: /usr/local/bin/entrypoint.sh
          args: conda info
      -
        name: test3
        uses: docker://richardslab/template_r_project:latest
        with:
          args: R -e 'library(dplyr); library(ggplot2);'





