name: docker-build-push

on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - main
env:
    dockerhub_repository: template_r_project
    dockerhub_organization: richardslab
jobs:
  test-github-run-template-r-project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run docker action and find env list in template project
        uses: yfarjoun/docker-run-action@main
        id: run-conda-env-main
        with:
          image: richardslab/template_r_project@sha256:5fdc3c8592f3ee97a55f290379efd74b75ad22363670dd8333b84024e640bbc6
          run: conda env list;
  variables:
    runs-on: ubuntu-latest
    outputs:
      date: ${{ steps.date.outputs.value }}
      branch_tag: ${{ steps.branch.outputs.value }}
      tag: ${{ steps.tags.outputs.value }}
    steps:
      - 
        name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v3.x
      -   
        name: Get current date
        id: date
        run: echo "::set-output name=value::$(date +'%Y-%m-%d')"
      - 
        name: Get Branch tag
        id: branch
        run: echo "::set-output name=value::${{env.dockerhub_organization}}/${{env.dockerhub_repository}}:${{steps.date.outputs.value}}_${{env.GITHUB_REF_SLUG}}"
      - 
        name: Get Latest tag
        id: latest
        run: echo "::set-output name=value::${{env.dockerhub_organization}}/${{env.dockerhub_repository}}:latest"
      - 
        uses: haya14busa/action-cond@v1
        id: tags
        with:
          cond: ${{ env.GITHUB_REF_SLUG == 'main' }}
          if_true: ${{env.branch_tag}}, ${{env.latest_tag}}
          if_false: ${{env.branch_tag}}
        env:
          branch_tag: ${{steps.branch.outputs.value}}
          latest_tag: ${{steps.latest.outputs.value}}
  build_docker:
    needs: variables
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      - 
        name: Show space available
        run: df -h .
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - 
        name: Show space available
        run: df -h .
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - 
        name: Show space available
        run: df -h .
      - 
        name: Get hash key for cache
        id: hash
        uses: theowenyoung/folder-hash@v2.0.1
        with:
          path: installation
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ steps.hash.outputs.hash }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Show space available
        run: df -h .
      -
        name: Show variables
        run: |
          echo date = ${{ needs.variables.outputs.date }}
          echo tags = ${{ needs.variables.outputs.tag }}
          echo branch = ${{ needs.variables.outputs.branch_tag }}
          echo hash = ${{ steps.hash.outputs.hash }}
      -
        name: Build and push branch
        uses: docker/build-push-action@v2
        with:
          context: installation
          push: true
          tags: ${{ needs.variables.outputs.tag }}
          builder: ${{ steps.buildx.outputs.name }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
  test_conda_with_farjoun_action:
    needs: [variables,build_docker]
    runs-on: ubuntu-latest
    steps:
      -
        uses: addnab/docker-run-action@v3
        with:
          image: richardslab/template_r_project:latest
          run: conda env list
          shell: ""
  test_conda_with_farjoun_action_branch:
    needs: [variables,build_docker]
    runs-on: ubuntu-latest
    steps:
      -
        uses: yfarjoun/docker-run-action@main
        with:
          image: ${{ needs.variables.outputs.branch_tag }}
          run: |
            conda env list
          shell: ""
  test_conda_info_with_farjoun_action:
    needs: [variables,build_docker]
    runs-on: ubuntu-latest
    steps:
      -
        uses: addnab/docker-run-action@v3
        with:
          image: ${{ needs.variables.outputs.branch_tag }}
          run: |
            echo "first line"
            echo "second line"
            conda env list
          shell: ""
  test_r_png:
    needs: [variables,build_docker]
    runs-on: ubuntu-latest
    container: ${{ needs.variables.outputs.branch_tag }} 
    steps:
      -
        name: Show space available
        run: df -h .
      -
        name: run docker test png
        uses: yfarjoun/docker-run-action@main
        with:
          image: ${{ needs.variables.outputs.branch_tag }}
          run: |
            Rscript -e 'png()' 
  test_r_2SMR:
    needs: [variables,build_docker]
    runs-on: ubuntu-latest
    container: ${{ needs.variables.outputs.branch_tag }} 
    steps:
      -
        name: run docker test two-sample-mr
        uses: yfarjoun/docker-run-action@main
        with:
          image: ${{ needs.variables.outputs.branch_tag }}
          run: | 
            Rscript -e 'library(ggplot2); library(dplyr)'
  



