name: R and Python Package using Conda and mamba

on: 
  pull_request:
  push:
    branches:
      - main-redacted

jobs:
  build-environment:
    name: Build Environment using Mamba
    runs-on: "ubuntu-latest"
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v2
      - 
        name: create-env
        run: installation/create_env.sh
      # - uses: conda-incubator/setup-miniconda@v2
      #   with:
      #     python-version: 3.6
      #     activate-environment: Template
      #     mamba-version: "*"
      #     channels: conda-forge,r,bioconda,defaults,anaconda
      #     channel-priority: true
      #     environment-file: installation/environment.yml
      # - name: post-conda-steps
      #   run: |
      #     installation/post_conda_steps.sh 
      -
        name: conda info
        run: conda info
      - name: More conda info
        run: |
          conda info --envs
          conda list -n Template
          conda config --show-sources
          conda config --show
          printenv | sort
      - name: test-r-libraries
        run: |
          conda activate Template
          R -e 'library(dplyr); library(ggplot2);'

